# Generated by Django 5.0.3 on 2024-03-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
                ('tipo', models.CharField(choices=[('INSTRUMENTOS', 'INSTRUMENTOS'), ('ACCESORIOS', 'ACCESORIOS')], max_length=50)),
                ('categoria', models.CharField(max_length=150)),
                ('precio', models.FloatField(max_length=150)),
            ],
        ),
    ]
