# Generated by Django 5.0.3 on 2024-03-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_product_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
